spring:
  application:
    name: encoding-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: encoding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.shopy_stream.encode_service.event.VideoUploadedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

# AWS Configuration
aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-southeast-2
  s3:
    bucket-name: shoppable-streaming-platform-888184097122-ap-southeast-2-an

# FFmpeg Configuration
ffmpeg:
  path: ${FFMPEG_PATH:C:/Users/Lenovo/OneDrive/Desktop/Shopy-stream-app/ffmpeg-8.1.1-essentials_build/bin/ffmpeg.exe}

# Temp directory for encoding
encoding:
  temp-dir: ${TEMP_DIR:C:/temp/encoding}

management:
  endpoints:
    web:
      exposure:
        include: health,info